[GSPREAD]
# This path is used only when running locally. In GitHub Actions, the file is created at the root.
SERVICE_ACCOUNT_FILE = credentials.json

# The name of the Google Sheet document.
SHEET_NAME = RSS_Feed_History

[NTFY]
# Your secret ntfy.sh topic.
TOPIC = your-ntfy-topic
