name: Check RSS Feeds

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual runs

jobs:
  check-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials file from Base64 secret
        run: echo "${{ secrets.GCP_CREDENTIALS_JSON }}" | base64 --decode > credentials.json

      - name: Create config.ini file from secrets
        run: |
          echo "[GSPREAD]" > config.ini
          echo "SERVICE_ACCOUNT_FILE = credentials.json" >> config.ini
          echo "SHEET_NAME = ${{ secrets.GSPREAD_SHEET_NAME }}" >> config.ini
          echo "" >> config.ini
          echo "[NTFY]" >> config.ini
          echo "TOPIC = ${{ secrets.NTFY_TOPIC }}" >> config.ini

      - name: Create urls.txt file from secret
        run: echo "${{ secrets.RSS_URLS }}" > urls.txt

      - name: Run the RSS notifier script
        run: python rss_notifier/main.py
